apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: kflask-api-dep
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kflask-api
  strategy:
    canary:
      steps:
      - setWeight: 50
      - analysis:
          templates:
          - templateName: cpu-usage-rate
      - pause:
          duration: 10m
      - setWeight: 50
  template:
    metadata:
      labels:
        app: kflask-api
    spec:
      containers:
        - name: kflask-api
          image: PROJECT/API
          readinessProbe:
            initialDelaySeconds: 10 # Initial delay until the readiness is tested
            periodSeconds: 5 # How often to test
            httpGet:
               path: /health
               port: 6000
          resources:
            limits:
              cpu: "250m"
              memory: "100Mi"
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: dbname
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: password
            - name: NATS_URL
              value: nats://my-nats.default:4222