apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: kflask-api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kflask-api-dep
  minReplicas: 1
  maxReplicas: 3 
  targetCPUUtilizationPercentage: 80