apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: pingpong-hpa
  namespace: main-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pingpong
  minReplicas: 1
  maxReplicas: 3 
  targetCPUUtilizationPercentage: 80