apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  namespace: main-app
  labels:
    app: postgres
spec:
  ports:
  - port: 5432
    name: web
  loadBalancerIP: None
  selector:
    app: postgres