apiVersion: apps/v1
kind: Deployment
metadata:
  name: timestamp-hash-dep
  namespace: main-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: timestamp-hash
  template:
    metadata:
      labels:
        app: timestamp-hash
    spec:
      volumes:
        - name: shared-timestamp
          persistentVolumeClaim:
            claimName: main-claim
        - name: config
          configMap:
           name: message-conf
      containers:
        - name: timestamp-writer
          image: kriegmachine/timestamp_writer
          resources:
            limits:
              cpu: "250m"
              memory: "100Mi"
          volumeMounts:
            - name: shared-timestamp
              mountPath: /files/
        - name: timestamp-display
          image: kriegmachine/timestamp_display
          resources:
            limits:
              cpu: "250m"
              memory: "100Mi"
          volumeMounts:
            - name: shared-timestamp
              mountPath: /files/
            - name: config
              mountPath: /conf/
              readOnly: true
          env:
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: message-conf
                  key: MESSAGE
