apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: timestamp-hash-hpa
  namespace: main-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: timestamp-hash-dep
  minReplicas: 1
  maxReplicas: 3 
  targetCPUUtilizationPercentage: 80