apiVersion: v1
kind: Service
metadata:
  name: timestamp-hash-svc
  namespace: main-app
spec:
  type: NodePort
  selector:
    app: timestamp-hash
  ports:
    - port: 80
      protocol: TCP
      targetPort: 5000