apiVersion: apps/v1
kind: Deployment

metadata:
  name: kflask-dep
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kflask
  template:
    metadata:
      labels:
        app: kflask
    spec:
      volumes:
        - name: shared-images
          persistentVolumeClaim:
            claimName: project-claim
      containers:
        - name: kflask
          image: PROJECT/BACKEND
          readinessProbe:
            initialDelaySeconds: 10 # Initial delay until the readiness is tested
            periodSeconds: 5 # How often to test
            httpGet:
               path: /health
               port: 5000
          resources:
            limits:
              cpu: "250m"
              memory: "100Mi"
          volumeMounts:
            - name: shared-images
              mountPath: /images/ # aa