apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: backend-ingress
  namespace: project
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /*
        backend:
          serviceName: kflask-svc
          servicePort: 80
      - path: /daily_image
        backend:
          serviceName: kflask-svc
          servicePort: 80
      - path: /new_todo
        backend:
          serviceName: kflask-svc
          servicePort: 80
      - path: /todos
        backend:
          serviceName: kflask-svc
          servicePort: 80