apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: backend-ingress
  namespace: project
  annotations:
    traefik.ingress.kubernetes.io/rule-type: "PathPrefixStrip"
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: kflask-svc
          servicePort: 80