name: Delete environment for deleted branch

on:
  delete:

jobs:
  build-publish-deploy:
    name: Delete namespace for branch
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        project_id: ${{ secrets.GKE_PROJECT_ID  }}

    - run: gcloud --quiet auth configure-docker
    - run: gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"

    - name: Delete namespace
      run: |-
        cd project
        kubectl delete namespace ${GITHUB_REF#refs/heads/} || true