name: Release project

on:
  push:

env:
  GKE_CLUSTER: dwk-cluster
  GKE_ZONE: europe-north1-b
  API_IMAGE: kflask-api
  BACKEND_IMAGE: kflask
  WTG_IMAGE: wtg


jobs:
  build-publish-deploy:
    name: Build, Publish and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        project_id: ${{ secrets.GKE_PROJECT_ID  }}

    - run: gcloud --quiet auth configure-docker
    - run: gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"

   
    - name: Build container
      run: |-
        docker build --tag "gcr.io/${{ secrets.GKE_PROJECT_ID }}/$API_IMAGE:$GITHUB_SHA" project/api/
        docker build --tag "gcr.io/${{ secrets.GKE_PROJECT_ID }}/$BACKEND_IMAGE:$GITHUB_SHA" project/backend/
        docker build --tag "gcr.io/${{ secrets.GKE_PROJECT_ID }}/$WTG_IMAGE:$GITHUB_SHA" project/wikipedia-todo-generator/

    - name: Publish
      run: |- 
        docker push "gcr.io/${{ secrets.GKE_PROJECT_ID }}/$API_IMAGE:$GITHUB_SHA"
        docker push "gcr.io/${{ secrets.GKE_PROJECT_ID }}/$BACKEND_IMAGE:$GITHUB_SHA"
        docker push "gcr.io/${{ secrets.GKE_PROJECT_ID }}/$WTG_IMAGE:$GITHUB_SHA"

    - name: Set up Kustomize
      run: |-
        curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
        chmod u+x ./kustomize

    - name: Change into project
      run: cd project
    - name: Deploy
      run: |-
        ./kustomize edit set image PROJECT/API_IMAGE=gcr.io/${{ secrets.GKE_PROJECT_ID }}/$API_IMAGE:$GITHUB_SHA
        ./kustomize edit set image PROJECT/BACKEND_IMAGE=gcr.io/${{ secrets.GKE_PROJECT_ID }}/$BACKEND_IMAGE:$GITHUB_SHA
        ./kustomize edit set image PROJECT/GENERATOR=gcr.io/${{ secrets.GKE_PROJECT_ID }}/$WTG_IMAGE:$GITHUB_SHA
        kubectl apply -k .