name: Release project

on:
  push:

env:
  GKE_CLUSTER: dwk-cluster
  GKE_ZONE: europe-north1-b
  API_IMAGE: kflask-api
  BACKEND_IMAGE: kflask
  WTG_IMAGE: wtg

jobs:
  build-publish-deploy:
    name: Build, Publish and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        project_id: ${{ secrets.GKE_PROJECT_ID }}

    - run: gcloud --quiet auth configure-docker
    - run: gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"

    - name: Create api image name and tag
      run: echo "::set-env name=API_IMAGE_WITH_TAG::gcr.io/${{ secrets.GKE_PROJECT }}/$API_IMAGE:${GITHUB_REF#refs/heads/}-$GITHUB_SHA"

    - name: Create backend image name and tag
      run: echo "::set-env name=BACKEND_IMAGE_WITH_TAG::gcr.io/${{ secrets.GKE_PROJECT }}/$BACKEND_IMAGE:${GITHUB_REF#refs/heads/}-$GITHUB_SHA"

    - name: Create wtg image name and tag
      run: echo "::set-env name=WTG_IMAGE_WITH_TAG::gcr.io/${{ secrets.GKE_PROJECT }}/$WTG_IMAGE:${GITHUB_REF#refs/heads/}-$GITHUB_SHA"

    - name: Build API
      run: docker build --tag "$API_IMAGE_WITH_TAG" ./project/api/

    - name: Build backend
      run: docker build --tag "$BACKEND_IMAGE_WITH_TAG" ./project/backend/

    - name: Build wtg
      run: docker build --tag "$WTG_IMAGE_WITH_TAG" ./project/wikipedia-todo-generator/

    - name: Publish
      run: docker push "$API_IMAGE_WITH_TAG"

    - name: Set up Kustomize
      run: |-
        curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
        chmod u+x ./kustomize

    - name: Deploy
      run: |-
        ./kustomize edit set image PROJECT/API_IMAGE=$API_IMAGE_WITH_TAG
        ./kustomize edit set image PROJECT/BACKEND_IMAGE=$BACKEND_IMAGE_WITH_TAG
        ./kustomize edit set image PROJECT/GENERATOR=$WTG_IMAGE_WITH_TAG
        ./kustomize edit set image DATABASE=postgres:13.0


        kubectl apply -k project/
        kubectl rollout status deployment $API_IMAGE  